### ISSUE TITLE
Récupération du texte

### ISSUE THREAD

**Issue by Leoglme** [Leoglme/nlp_travel_order_resolver#1]
Développer une fonctionnalité permettant de lire et traiter du texte à partir de fichiers texte ou d'une URL, en s'assurant de la compatibilité avec l'encodage UTF-8

**Comment by epitechBR** [comment]
12/09/2024 13:59:52 - creation of the 1-Rcupration-du-texte branch and branch link to issue 1 - Riandiere benoit

**Comment by epitechBR** [comment]
12/09/2024 14:05:01 - création de la branche 1-Rcupration-du-texte et lien avec l'issue 1 - Riandiere benoit

**Comment by epitechBR** [comment]
12/09/2024 15:18:15 - création de la branche 1-Rcupration-du-texte et lien avec l'issue 1 - Riandiere benoit

**Comment by epitechBR** [comment]
12/09/2024 15:19:57 - création de la branche 1-Rcupration-du-texte et lien avec l'issue 1 - Riandiere benoit

**Comment by epitechBR** [comment]
12/09/2024 15:22:19 - création de la branche 1-Rcupration-du-texte et lien avec l'issue 1 - Riandiere benoit
